name: angels_share
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-179.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  onboarding: ^3.1.0
  google_fonts: ^4.0.3
  flutter_speed_dial: ^6.2.0
  icloud_storage: ^2.2.0
  sqflite: ^2.2.4+1
  path_provider: ^2.0.13
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: Custom
      fonts:
        - asset: fonts/Custom.ttf

